## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.3.1+cu121


## Introduction to Tensors

### Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,4],
                        [3,5,4],
                        [4,0,9],
                         [3,1,1]]])
TENSOR

tensor([[[1, 2, 4],
         [3, 5, 4],
         [4, 0, 9],
         [3, 1, 1]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 4, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 4],
        [3, 5, 4],
        [4, 0, 9],
        [3, 1, 1]])

### Random Tensors

Why Random Tensors?
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [18]:
# Create a random tensors of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6564, 0.2818, 0.6144, 0.7349],
        [0.3335, 0.2975, 0.4559, 0.5593],
        [0.1405, 0.4352, 0.6484, 0.7239]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
# Create a random tensor tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3,224,224))  # height, width, colour channels (R,G,B)
random_image_size_tensor, random_image_size_tensor.shape, random_image_size_tensor.ndim

(tensor([[[0.2811, 0.4806, 0.9714,  ..., 0.0770, 0.7502, 0.4533],
          [0.5705, 0.7543, 0.0468,  ..., 0.7956, 0.2016, 0.1682],
          [0.9571, 0.4203, 0.6640,  ..., 0.5207, 0.0932, 0.5987],
          ...,
          [0.2405, 0.1475, 0.3547,  ..., 0.6304, 0.3158, 0.3931],
          [0.5837, 0.1696, 0.5115,  ..., 0.6880, 0.0549, 0.2826],
          [0.4773, 0.3272, 0.6181,  ..., 0.5363, 0.2889, 0.7784]],
 
         [[0.9304, 0.7297, 0.0154,  ..., 0.2072, 0.8319, 0.7607],
          [0.6706, 0.7926, 0.7544,  ..., 0.5620, 0.8364, 0.8197],
          [0.2623, 0.1350, 0.3107,  ..., 0.8389, 0.5672, 0.6085],
          ...,
          [0.6150, 0.5733, 0.8825,  ..., 0.1268, 0.8311, 0.0692],
          [0.2094, 0.2630, 0.9380,  ..., 0.0673, 0.4489, 0.6574],
          [0.9723, 0.9626, 0.8695,  ..., 0.9973, 0.0867, 0.2820]],
 
         [[0.4868, 0.4174, 0.0474,  ..., 0.0331, 0.2208, 0.9797],
          [0.5844, 0.6940, 0.5524,  ..., 0.4865, 0.7271, 0.4716],
          [0.7928, 0.4952, 0.8441,  ...,

In [22]:
torch.rand(size=(3,3))

tensor([[0.9014, 0.8001, 0.9678],
        [0.5001, 0.3260, 0.7931],
        [0.3560, 0.0507, 0.5846]])

### Zero's and one's

In [23]:
# Tensor with all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype
zeros.dtype
random_tensor.dtype
random_image_size_tensor.dtype

torch.float32

### Create a Range of Tensors and Tensor-like

In [26]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# Createing tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
Tensor Datatypes are the 3 big errors with PyTorch.
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on the right device.

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Datatype of tensor(e.g float16, float32)
                               device=None, # What device is tensor on.
                               requires_grad=False) # Whether or not to track gradients with this tensor operations.
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensor (Tensor Attributes)
1. Tensors not right datatype - to get datatype from tensor, can use 'tensor.dtype'.
2. Tensors not right shape. - to get shape from tensor, can use 'tensor.shape'.
3. Tensors not on the right device. - to get device from tensor, can use 'tensor.device'.

In [34]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3318, 0.4921, 0.7050, 0.7156],
        [0.1433, 1.0000, 0.9364, 0.2601],
        [0.0351, 0.7683, 0.6789, 0.3997]])

In [35]:
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device of Tensor: {some_tensor.device}")

tensor([[0.3318, 0.4921, 0.7050, 0.7156],
        [0.1433, 1.0000, 0.9364, 0.2601],
        [0.0351, 0.7683, 0.6789, 0.3997]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device of Tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [36]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
tensor * 5

tensor([ 5, 10, 15])

In [39]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [40]:
# PuTorch Inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 5)

tensor([6, 7, 8])

### Matrix Multiplication

Two ways of multiplication in NN and DL.
1. Element-wise Multiplication
2. Matrix Multiplication(Dot product)

There are two main rules for matrix multiplication:
1. The **Inner Dimensions** must match:
* (3,2) @ (3,2) won't work
* (2,3) @ (3,2) will work
2. The resulting matrix has shape of the **Outer Dimensions**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

In [42]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
# Matrix Multiplication by hand
1*1+2*2+3*3

14

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.6 ms, sys: 0 ns, total: 1.6 ms
Wall time: 1.69 ms


In [46]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 143 µs, sys: 21 µs, total: 164 µs
Wall time: 101 µs


tensor(14)

### One of the most common error in DL: shape errors

In [47]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # mm is same as matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix tensor shape issues, we can manipulate the shape of our tensors using a **transpose**.

In [49]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [50]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [51]:
# The matrix multiplication operation works when tensor_B is transposed.
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensor aggregation)

In [53]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [55]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
# torch.mean() function requires a tensor of float32 datatype.
torch.mean(x.type(torch.float32))

tensor(45.)

In [60]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [62]:
# Find the index value of minimum value
x.argmin()

tensor(0)

In [63]:
# Find the index value of minimum value
x.argmax()

tensor(9)

### Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - Combine multiple tensor on top of eachother(vstack) or side by side(hstack).
* Squeeze - Removes all '1' dimensions from a tensor.
* Unsqueeze - add a '1' dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [86]:
import torch
x =torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [89]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [90]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x], dim =1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [91]:
# torch.squeeze - removes all single dimensions from a target tensor
print(f"Previous Tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [92]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [93]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width,colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [94]:
x_original[0,0,0] = 24523
x_original[0,0,0], x_permuted[0,0,0]

(tensor(24523.), tensor(24523.))

## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [95]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [96]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [99]:
x[0][0]

tensor([1, 2, 3])

In [104]:
x[0][2][2]

tensor(9)

In [110]:
x[ : , : , : ]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [108]:
# Use ":" to select all of target dimension
x[ : , 0:3 , 1:2]

tensor([[[2],
         [5],
         [8]]])

In [109]:
x[:, 1, :]

tensor([[4, 5, 6]])

In [111]:
x[:, 2, 2]

tensor([9])

In [112]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch's Tensor and NumPy

* Data in NumPy, want in PyTorch tensor -> torch.fromnumpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [113]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [114]:
array.dtype

dtype('float64')

In [115]:
tensor.dtype

torch.float64

In [116]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [117]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [118]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

starts with random numbers -> tensor operation -> update random numbers to try and make them of the data -> again -> again -> again..

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed** (manual_seed)


In [119]:
torch.rand(3,3)

tensor([[0.0230, 0.8848, 0.4783],
        [0.2788, 0.3161, 0.4817],
        [0.2422, 0.3696, 0.8835]])

In [120]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0801, 0.2167, 0.8967, 0.1528],
        [0.6152, 0.9429, 0.3135, 0.9665],
        [0.5415, 0.6239, 0.9267, 0.1926]])
tensor([[0.7280, 0.9283, 0.7378, 0.4898],
        [0.5589, 0.7000, 0.6228, 0.8062],
        [0.5816, 0.3050, 0.1766, 0.5203]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [122]:
# Let's make random but reproducible tensors
# Set the random random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch Objects on GPU's (and making faster computations)



In [1]:
### 1. Getting the GPU

!nvidia-smi

Mon Jul 29 10:10:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

## Putting Tensors (and models) on the GPU for faster computations.

In [7]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
# Move tensor back to the cpu
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
# We can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')