# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
tensor0 = torch.randn(7 ,7)
tensor0.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensor1 = torch.randn(1, 7)
print(tensor1)

# Perform matrix multiplication
tensor2 = tensor1 * 2
print(tensor2)

tensor([[ 1.5191,  0.1460,  0.5334, -1.3034,  1.6996,  0.2008,  0.3356]])
tensor([[ 3.0381,  0.2920,  1.0668, -2.6068,  3.3992,  0.4017,  0.6712]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor3 = torch.randn(7, 7)
tensor4 = torch.randn(1, 7)

# Matrix multiply tensors
tensor5 = torch.matmul(tensor3, tensor4.T)
tensor5

tensor([[ 3.5168],
        [ 2.1984],
        [-1.7815],
        [ 3.8600],
        [-1.5010],
        [-1.6916],
        [-2.9352]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device_info = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device_info.type)

# Create two random tensors on GPU
tensor6 = torch.randn(2, 3)
tensor7 = torch.randn(2, 3)
print(tensor6)
print(tensor7)

cuda
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])
tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
tensor8 = torch.matmul(tensor6, tensor7.T)
tensor8, tensor8.device, tensor8.shape

(tensor([[ 0.5595,  0.4036],
         [-0.5087,  0.2792]]),
 device(type='cpu'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
max = torch.max(tensor8)

# Find min
min = torch.min(tensor8)
max, min

(tensor(0.5595), tensor(-0.5087))

### 9. Find the maximum and minimum index values of the output of 7.

In [33]:
# Find arg max
argmax = torch.argmax(tensor8)

# Find arg min
argmin = torch.argmin(tensor8)
argmax, argmin

(tensor(0), tensor(2))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [35]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor9 = torch.randn(1, 1, 1, 10)

# Remove single dimensions
tensor10 = torch.squeeze(tensor9)

# Print out tensors and their shapes
print(f"Tensor: {tensor9} | Tensor Shape: {tensor9.shape}")
print(f"Tensor: {tensor10} | Tensor Shape: {tensor10.shape}")

Tensor: tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) | Tensor Shape: torch.Size([1, 1, 1, 10])
Tensor: tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]) | Tensor Shape: torch.Size([10])
